[package]
name = "foo"
version = "0.1.0"
authors = ["Jiacai Liu <dev@liujiacai.net>"]
edition = "2021"

[dependencies]
env_logger = "0.10.0"
log = "0.4.19"
reqwest = { version = "0.11.18", default-features = false }
tokio = { version = "1.29.1", features= ["full"] }
